# Generated by Django 3.1.7 on 2022-04-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dni',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
